/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsMcpRouteImport } from './routes/settings.mcp'
import { Route as PShareTokenRouteImport } from './routes/p.$shareToken'
import { Route as ProjectsIdOverviewRouteImport } from './routes/projects.$id.overview'
import { Route as ProjectsIdNotesRouteImport } from './routes/projects.$id.notes'
import { Route as ProjectsIdInboxRouteImport } from './routes/projects.$id.inbox'
import { Route as ProjectsIdGoalsRouteImport } from './routes/projects.$id.goals'
import { Route as ProjectsIdFlowRouteImport } from './routes/projects.$id.flow'
import { Route as ProjectsIdBoardRouteImport } from './routes/projects.$id.board'
import { Route as ProjectsIdNotesIndexRouteImport } from './routes/projects.$id.notes.index'
import { Route as ProjectsIdDocumentsIndexRouteImport } from './routes/projects.$id.documents.index'
import { Route as ProjectsIdNotesNoteIdRouteImport } from './routes/projects.$id.notes.$noteId'
import { Route as ProjectsIdDocumentsDocIdRouteImport } from './routes/projects.$id.documents.$docId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMcpRoute = SettingsMcpRouteImport.update({
  id: '/settings/mcp',
  path: '/settings/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PShareTokenRoute = PShareTokenRouteImport.update({
  id: '/p/$shareToken',
  path: '/p/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdOverviewRoute = ProjectsIdOverviewRouteImport.update({
  id: '/projects/$id/overview',
  path: '/projects/$id/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdNotesRoute = ProjectsIdNotesRouteImport.update({
  id: '/projects/$id/notes',
  path: '/projects/$id/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdInboxRoute = ProjectsIdInboxRouteImport.update({
  id: '/projects/$id/inbox',
  path: '/projects/$id/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdGoalsRoute = ProjectsIdGoalsRouteImport.update({
  id: '/projects/$id/goals',
  path: '/projects/$id/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdFlowRoute = ProjectsIdFlowRouteImport.update({
  id: '/projects/$id/flow',
  path: '/projects/$id/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdBoardRoute = ProjectsIdBoardRouteImport.update({
  id: '/projects/$id/board',
  path: '/projects/$id/board',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdNotesIndexRoute = ProjectsIdNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsIdNotesRoute,
} as any)
const ProjectsIdDocumentsIndexRoute =
  ProjectsIdDocumentsIndexRouteImport.update({
    id: '/projects/$id/documents/',
    path: '/projects/$id/documents/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsIdNotesNoteIdRoute = ProjectsIdNotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => ProjectsIdNotesRoute,
} as any)
const ProjectsIdDocumentsDocIdRoute =
  ProjectsIdDocumentsDocIdRouteImport.update({
    id: '/projects/$id/documents/$docId',
    path: '/projects/$id/documents/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/p/$shareToken': typeof PShareTokenRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/projects/$id/board': typeof ProjectsIdBoardRoute
  '/projects/$id/flow': typeof ProjectsIdFlowRoute
  '/projects/$id/goals': typeof ProjectsIdGoalsRoute
  '/projects/$id/inbox': typeof ProjectsIdInboxRoute
  '/projects/$id/notes': typeof ProjectsIdNotesRouteWithChildren
  '/projects/$id/overview': typeof ProjectsIdOverviewRoute
  '/projects/$id/documents/$docId': typeof ProjectsIdDocumentsDocIdRoute
  '/projects/$id/notes/$noteId': typeof ProjectsIdNotesNoteIdRoute
  '/projects/$id/documents/': typeof ProjectsIdDocumentsIndexRoute
  '/projects/$id/notes/': typeof ProjectsIdNotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/p/$shareToken': typeof PShareTokenRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/projects/$id/board': typeof ProjectsIdBoardRoute
  '/projects/$id/flow': typeof ProjectsIdFlowRoute
  '/projects/$id/goals': typeof ProjectsIdGoalsRoute
  '/projects/$id/inbox': typeof ProjectsIdInboxRoute
  '/projects/$id/overview': typeof ProjectsIdOverviewRoute
  '/projects/$id/documents/$docId': typeof ProjectsIdDocumentsDocIdRoute
  '/projects/$id/notes/$noteId': typeof ProjectsIdNotesNoteIdRoute
  '/projects/$id/documents': typeof ProjectsIdDocumentsIndexRoute
  '/projects/$id/notes': typeof ProjectsIdNotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/p/$shareToken': typeof PShareTokenRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/projects/$id/board': typeof ProjectsIdBoardRoute
  '/projects/$id/flow': typeof ProjectsIdFlowRoute
  '/projects/$id/goals': typeof ProjectsIdGoalsRoute
  '/projects/$id/inbox': typeof ProjectsIdInboxRoute
  '/projects/$id/notes': typeof ProjectsIdNotesRouteWithChildren
  '/projects/$id/overview': typeof ProjectsIdOverviewRoute
  '/projects/$id/documents/$docId': typeof ProjectsIdDocumentsDocIdRoute
  '/projects/$id/notes/$noteId': typeof ProjectsIdNotesNoteIdRoute
  '/projects/$id/documents/': typeof ProjectsIdDocumentsIndexRoute
  '/projects/$id/notes/': typeof ProjectsIdNotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/p/$shareToken'
    | '/settings/mcp'
    | '/projects/$id/board'
    | '/projects/$id/flow'
    | '/projects/$id/goals'
    | '/projects/$id/inbox'
    | '/projects/$id/notes'
    | '/projects/$id/overview'
    | '/projects/$id/documents/$docId'
    | '/projects/$id/notes/$noteId'
    | '/projects/$id/documents/'
    | '/projects/$id/notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/p/$shareToken'
    | '/settings/mcp'
    | '/projects/$id/board'
    | '/projects/$id/flow'
    | '/projects/$id/goals'
    | '/projects/$id/inbox'
    | '/projects/$id/overview'
    | '/projects/$id/documents/$docId'
    | '/projects/$id/notes/$noteId'
    | '/projects/$id/documents'
    | '/projects/$id/notes'
  id:
    | '__root__'
    | '/'
    | '/p/$shareToken'
    | '/settings/mcp'
    | '/projects/$id/board'
    | '/projects/$id/flow'
    | '/projects/$id/goals'
    | '/projects/$id/inbox'
    | '/projects/$id/notes'
    | '/projects/$id/overview'
    | '/projects/$id/documents/$docId'
    | '/projects/$id/notes/$noteId'
    | '/projects/$id/documents/'
    | '/projects/$id/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PShareTokenRoute: typeof PShareTokenRoute
  SettingsMcpRoute: typeof SettingsMcpRoute
  ProjectsIdBoardRoute: typeof ProjectsIdBoardRoute
  ProjectsIdFlowRoute: typeof ProjectsIdFlowRoute
  ProjectsIdGoalsRoute: typeof ProjectsIdGoalsRoute
  ProjectsIdInboxRoute: typeof ProjectsIdInboxRoute
  ProjectsIdNotesRoute: typeof ProjectsIdNotesRouteWithChildren
  ProjectsIdOverviewRoute: typeof ProjectsIdOverviewRoute
  ProjectsIdDocumentsDocIdRoute: typeof ProjectsIdDocumentsDocIdRoute
  ProjectsIdDocumentsIndexRoute: typeof ProjectsIdDocumentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/mcp': {
      id: '/settings/mcp'
      path: '/settings/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof SettingsMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$shareToken': {
      id: '/p/$shareToken'
      path: '/p/$shareToken'
      fullPath: '/p/$shareToken'
      preLoaderRoute: typeof PShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/overview': {
      id: '/projects/$id/overview'
      path: '/projects/$id/overview'
      fullPath: '/projects/$id/overview'
      preLoaderRoute: typeof ProjectsIdOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/notes': {
      id: '/projects/$id/notes'
      path: '/projects/$id/notes'
      fullPath: '/projects/$id/notes'
      preLoaderRoute: typeof ProjectsIdNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/inbox': {
      id: '/projects/$id/inbox'
      path: '/projects/$id/inbox'
      fullPath: '/projects/$id/inbox'
      preLoaderRoute: typeof ProjectsIdInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/goals': {
      id: '/projects/$id/goals'
      path: '/projects/$id/goals'
      fullPath: '/projects/$id/goals'
      preLoaderRoute: typeof ProjectsIdGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/flow': {
      id: '/projects/$id/flow'
      path: '/projects/$id/flow'
      fullPath: '/projects/$id/flow'
      preLoaderRoute: typeof ProjectsIdFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/board': {
      id: '/projects/$id/board'
      path: '/projects/$id/board'
      fullPath: '/projects/$id/board'
      preLoaderRoute: typeof ProjectsIdBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/notes/': {
      id: '/projects/$id/notes/'
      path: '/'
      fullPath: '/projects/$id/notes/'
      preLoaderRoute: typeof ProjectsIdNotesIndexRouteImport
      parentRoute: typeof ProjectsIdNotesRoute
    }
    '/projects/$id/documents/': {
      id: '/projects/$id/documents/'
      path: '/projects/$id/documents'
      fullPath: '/projects/$id/documents/'
      preLoaderRoute: typeof ProjectsIdDocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/notes/$noteId': {
      id: '/projects/$id/notes/$noteId'
      path: '/$noteId'
      fullPath: '/projects/$id/notes/$noteId'
      preLoaderRoute: typeof ProjectsIdNotesNoteIdRouteImport
      parentRoute: typeof ProjectsIdNotesRoute
    }
    '/projects/$id/documents/$docId': {
      id: '/projects/$id/documents/$docId'
      path: '/projects/$id/documents/$docId'
      fullPath: '/projects/$id/documents/$docId'
      preLoaderRoute: typeof ProjectsIdDocumentsDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectsIdNotesRouteChildren {
  ProjectsIdNotesNoteIdRoute: typeof ProjectsIdNotesNoteIdRoute
  ProjectsIdNotesIndexRoute: typeof ProjectsIdNotesIndexRoute
}

const ProjectsIdNotesRouteChildren: ProjectsIdNotesRouteChildren = {
  ProjectsIdNotesNoteIdRoute: ProjectsIdNotesNoteIdRoute,
  ProjectsIdNotesIndexRoute: ProjectsIdNotesIndexRoute,
}

const ProjectsIdNotesRouteWithChildren = ProjectsIdNotesRoute._addFileChildren(
  ProjectsIdNotesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PShareTokenRoute: PShareTokenRoute,
  SettingsMcpRoute: SettingsMcpRoute,
  ProjectsIdBoardRoute: ProjectsIdBoardRoute,
  ProjectsIdFlowRoute: ProjectsIdFlowRoute,
  ProjectsIdGoalsRoute: ProjectsIdGoalsRoute,
  ProjectsIdInboxRoute: ProjectsIdInboxRoute,
  ProjectsIdNotesRoute: ProjectsIdNotesRouteWithChildren,
  ProjectsIdOverviewRoute: ProjectsIdOverviewRoute,
  ProjectsIdDocumentsDocIdRoute: ProjectsIdDocumentsDocIdRoute,
  ProjectsIdDocumentsIndexRoute: ProjectsIdDocumentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
