/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as SettingsWorkspacesRouteImport } from './routes/settings.workspaces'
import { Route as SettingsMembersRouteImport } from './routes/settings.members'
import { Route as SettingsMcpRouteImport } from './routes/settings.mcp'
import { Route as PShareTokenRouteImport } from './routes/p.$shareToken'
import { Route as InviteInvitationIdRouteImport } from './routes/invite.$invitationId'
import { Route as PShareTokenIndexRouteImport } from './routes/p.$shareToken.index'
import { Route as ProjectsIdOverviewRouteImport } from './routes/projects.$id.overview'
import { Route as ProjectsIdNotesRouteImport } from './routes/projects.$id.notes'
import { Route as ProjectsIdListRouteImport } from './routes/projects.$id.list'
import { Route as ProjectsIdInboxRouteImport } from './routes/projects.$id.inbox'
import { Route as ProjectsIdGoalsRouteImport } from './routes/projects.$id.goals'
import { Route as ProjectsIdFlowRouteImport } from './routes/projects.$id.flow'
import { Route as ProjectsIdBoardRouteImport } from './routes/projects.$id.board'
import { Route as PShareTokenPrototypesRouteImport } from './routes/p.$shareToken.prototypes'
import { Route as ProjectsIdPrototypesIndexRouteImport } from './routes/projects.$id.prototypes.index'
import { Route as ProjectsIdNotesIndexRouteImport } from './routes/projects.$id.notes.index'
import { Route as ProjectsIdDocumentsIndexRouteImport } from './routes/projects.$id.documents.index'
import { Route as PShareTokenPrototypesIndexRouteImport } from './routes/p.$shareToken.prototypes.index'
import { Route as ProjectsIdPrototypesPrototypeIdRouteImport } from './routes/projects.$id.prototypes.$prototypeId'
import { Route as ProjectsIdNotesNoteIdRouteImport } from './routes/projects.$id.notes.$noteId'
import { Route as ProjectsIdDocumentsDocIdRouteImport } from './routes/projects.$id.documents.$docId'
import { Route as PShareTokenPrototypesPrototypeIdRouteImport } from './routes/p.$shareToken.prototypes.$prototypeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWorkspacesRoute = SettingsWorkspacesRouteImport.update({
  id: '/settings/workspaces',
  path: '/settings/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMembersRoute = SettingsMembersRouteImport.update({
  id: '/settings/members',
  path: '/settings/members',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMcpRoute = SettingsMcpRouteImport.update({
  id: '/settings/mcp',
  path: '/settings/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PShareTokenRoute = PShareTokenRouteImport.update({
  id: '/p/$shareToken',
  path: '/p/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteInvitationIdRoute = InviteInvitationIdRouteImport.update({
  id: '/invite/$invitationId',
  path: '/invite/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const PShareTokenIndexRoute = PShareTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PShareTokenRoute,
} as any)
const ProjectsIdOverviewRoute = ProjectsIdOverviewRouteImport.update({
  id: '/projects/$id/overview',
  path: '/projects/$id/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdNotesRoute = ProjectsIdNotesRouteImport.update({
  id: '/projects/$id/notes',
  path: '/projects/$id/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdListRoute = ProjectsIdListRouteImport.update({
  id: '/projects/$id/list',
  path: '/projects/$id/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdInboxRoute = ProjectsIdInboxRouteImport.update({
  id: '/projects/$id/inbox',
  path: '/projects/$id/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdGoalsRoute = ProjectsIdGoalsRouteImport.update({
  id: '/projects/$id/goals',
  path: '/projects/$id/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdFlowRoute = ProjectsIdFlowRouteImport.update({
  id: '/projects/$id/flow',
  path: '/projects/$id/flow',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdBoardRoute = ProjectsIdBoardRouteImport.update({
  id: '/projects/$id/board',
  path: '/projects/$id/board',
  getParentRoute: () => rootRouteImport,
} as any)
const PShareTokenPrototypesRoute = PShareTokenPrototypesRouteImport.update({
  id: '/prototypes',
  path: '/prototypes',
  getParentRoute: () => PShareTokenRoute,
} as any)
const ProjectsIdPrototypesIndexRoute =
  ProjectsIdPrototypesIndexRouteImport.update({
    id: '/projects/$id/prototypes/',
    path: '/projects/$id/prototypes/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsIdNotesIndexRoute = ProjectsIdNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsIdNotesRoute,
} as any)
const ProjectsIdDocumentsIndexRoute =
  ProjectsIdDocumentsIndexRouteImport.update({
    id: '/projects/$id/documents/',
    path: '/projects/$id/documents/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PShareTokenPrototypesIndexRoute =
  PShareTokenPrototypesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PShareTokenPrototypesRoute,
  } as any)
const ProjectsIdPrototypesPrototypeIdRoute =
  ProjectsIdPrototypesPrototypeIdRouteImport.update({
    id: '/projects/$id/prototypes/$prototypeId',
    path: '/projects/$id/prototypes/$prototypeId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsIdNotesNoteIdRoute = ProjectsIdNotesNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => ProjectsIdNotesRoute,
} as any)
const ProjectsIdDocumentsDocIdRoute =
  ProjectsIdDocumentsDocIdRouteImport.update({
    id: '/projects/$id/documents/$docId',
    path: '/projects/$id/documents/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PShareTokenPrototypesPrototypeIdRoute =
  PShareTokenPrototypesPrototypeIdRouteImport.update({
    id: '/$prototypeId',
    path: '/$prototypeId',
    getParentRoute: () => PShareTokenPrototypesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/p/$shareToken': typeof PShareTokenRouteWithChildren
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/members': typeof SettingsMembersRoute
  '/settings/workspaces': typeof SettingsWorkspacesRoute
  '/projects/': typeof ProjectsIndexRoute
  '/p/$shareToken/prototypes': typeof PShareTokenPrototypesRouteWithChildren
  '/projects/$id/board': typeof ProjectsIdBoardRoute
  '/projects/$id/flow': typeof ProjectsIdFlowRoute
  '/projects/$id/goals': typeof ProjectsIdGoalsRoute
  '/projects/$id/inbox': typeof ProjectsIdInboxRoute
  '/projects/$id/list': typeof ProjectsIdListRoute
  '/projects/$id/notes': typeof ProjectsIdNotesRouteWithChildren
  '/projects/$id/overview': typeof ProjectsIdOverviewRoute
  '/p/$shareToken/': typeof PShareTokenIndexRoute
  '/p/$shareToken/prototypes/$prototypeId': typeof PShareTokenPrototypesPrototypeIdRoute
  '/projects/$id/documents/$docId': typeof ProjectsIdDocumentsDocIdRoute
  '/projects/$id/notes/$noteId': typeof ProjectsIdNotesNoteIdRoute
  '/projects/$id/prototypes/$prototypeId': typeof ProjectsIdPrototypesPrototypeIdRoute
  '/p/$shareToken/prototypes/': typeof PShareTokenPrototypesIndexRoute
  '/projects/$id/documents/': typeof ProjectsIdDocumentsIndexRoute
  '/projects/$id/notes/': typeof ProjectsIdNotesIndexRoute
  '/projects/$id/prototypes/': typeof ProjectsIdPrototypesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/members': typeof SettingsMembersRoute
  '/settings/workspaces': typeof SettingsWorkspacesRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$id/board': typeof ProjectsIdBoardRoute
  '/projects/$id/flow': typeof ProjectsIdFlowRoute
  '/projects/$id/goals': typeof ProjectsIdGoalsRoute
  '/projects/$id/inbox': typeof ProjectsIdInboxRoute
  '/projects/$id/list': typeof ProjectsIdListRoute
  '/projects/$id/overview': typeof ProjectsIdOverviewRoute
  '/p/$shareToken': typeof PShareTokenIndexRoute
  '/p/$shareToken/prototypes/$prototypeId': typeof PShareTokenPrototypesPrototypeIdRoute
  '/projects/$id/documents/$docId': typeof ProjectsIdDocumentsDocIdRoute
  '/projects/$id/notes/$noteId': typeof ProjectsIdNotesNoteIdRoute
  '/projects/$id/prototypes/$prototypeId': typeof ProjectsIdPrototypesPrototypeIdRoute
  '/p/$shareToken/prototypes': typeof PShareTokenPrototypesIndexRoute
  '/projects/$id/documents': typeof ProjectsIdDocumentsIndexRoute
  '/projects/$id/notes': typeof ProjectsIdNotesIndexRoute
  '/projects/$id/prototypes': typeof ProjectsIdPrototypesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/p/$shareToken': typeof PShareTokenRouteWithChildren
  '/settings/mcp': typeof SettingsMcpRoute
  '/settings/members': typeof SettingsMembersRoute
  '/settings/workspaces': typeof SettingsWorkspacesRoute
  '/projects/': typeof ProjectsIndexRoute
  '/p/$shareToken/prototypes': typeof PShareTokenPrototypesRouteWithChildren
  '/projects/$id/board': typeof ProjectsIdBoardRoute
  '/projects/$id/flow': typeof ProjectsIdFlowRoute
  '/projects/$id/goals': typeof ProjectsIdGoalsRoute
  '/projects/$id/inbox': typeof ProjectsIdInboxRoute
  '/projects/$id/list': typeof ProjectsIdListRoute
  '/projects/$id/notes': typeof ProjectsIdNotesRouteWithChildren
  '/projects/$id/overview': typeof ProjectsIdOverviewRoute
  '/p/$shareToken/': typeof PShareTokenIndexRoute
  '/p/$shareToken/prototypes/$prototypeId': typeof PShareTokenPrototypesPrototypeIdRoute
  '/projects/$id/documents/$docId': typeof ProjectsIdDocumentsDocIdRoute
  '/projects/$id/notes/$noteId': typeof ProjectsIdNotesNoteIdRoute
  '/projects/$id/prototypes/$prototypeId': typeof ProjectsIdPrototypesPrototypeIdRoute
  '/p/$shareToken/prototypes/': typeof PShareTokenPrototypesIndexRoute
  '/projects/$id/documents/': typeof ProjectsIdDocumentsIndexRoute
  '/projects/$id/notes/': typeof ProjectsIdNotesIndexRoute
  '/projects/$id/prototypes/': typeof ProjectsIdPrototypesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invite/$invitationId'
    | '/p/$shareToken'
    | '/settings/mcp'
    | '/settings/members'
    | '/settings/workspaces'
    | '/projects/'
    | '/p/$shareToken/prototypes'
    | '/projects/$id/board'
    | '/projects/$id/flow'
    | '/projects/$id/goals'
    | '/projects/$id/inbox'
    | '/projects/$id/list'
    | '/projects/$id/notes'
    | '/projects/$id/overview'
    | '/p/$shareToken/'
    | '/p/$shareToken/prototypes/$prototypeId'
    | '/projects/$id/documents/$docId'
    | '/projects/$id/notes/$noteId'
    | '/projects/$id/prototypes/$prototypeId'
    | '/p/$shareToken/prototypes/'
    | '/projects/$id/documents/'
    | '/projects/$id/notes/'
    | '/projects/$id/prototypes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invite/$invitationId'
    | '/settings/mcp'
    | '/settings/members'
    | '/settings/workspaces'
    | '/projects'
    | '/projects/$id/board'
    | '/projects/$id/flow'
    | '/projects/$id/goals'
    | '/projects/$id/inbox'
    | '/projects/$id/list'
    | '/projects/$id/overview'
    | '/p/$shareToken'
    | '/p/$shareToken/prototypes/$prototypeId'
    | '/projects/$id/documents/$docId'
    | '/projects/$id/notes/$noteId'
    | '/projects/$id/prototypes/$prototypeId'
    | '/p/$shareToken/prototypes'
    | '/projects/$id/documents'
    | '/projects/$id/notes'
    | '/projects/$id/prototypes'
  id:
    | '__root__'
    | '/'
    | '/invite/$invitationId'
    | '/p/$shareToken'
    | '/settings/mcp'
    | '/settings/members'
    | '/settings/workspaces'
    | '/projects/'
    | '/p/$shareToken/prototypes'
    | '/projects/$id/board'
    | '/projects/$id/flow'
    | '/projects/$id/goals'
    | '/projects/$id/inbox'
    | '/projects/$id/list'
    | '/projects/$id/notes'
    | '/projects/$id/overview'
    | '/p/$shareToken/'
    | '/p/$shareToken/prototypes/$prototypeId'
    | '/projects/$id/documents/$docId'
    | '/projects/$id/notes/$noteId'
    | '/projects/$id/prototypes/$prototypeId'
    | '/p/$shareToken/prototypes/'
    | '/projects/$id/documents/'
    | '/projects/$id/notes/'
    | '/projects/$id/prototypes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InviteInvitationIdRoute: typeof InviteInvitationIdRoute
  PShareTokenRoute: typeof PShareTokenRouteWithChildren
  SettingsMcpRoute: typeof SettingsMcpRoute
  SettingsMembersRoute: typeof SettingsMembersRoute
  SettingsWorkspacesRoute: typeof SettingsWorkspacesRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsIdBoardRoute: typeof ProjectsIdBoardRoute
  ProjectsIdFlowRoute: typeof ProjectsIdFlowRoute
  ProjectsIdGoalsRoute: typeof ProjectsIdGoalsRoute
  ProjectsIdInboxRoute: typeof ProjectsIdInboxRoute
  ProjectsIdListRoute: typeof ProjectsIdListRoute
  ProjectsIdNotesRoute: typeof ProjectsIdNotesRouteWithChildren
  ProjectsIdOverviewRoute: typeof ProjectsIdOverviewRoute
  ProjectsIdDocumentsDocIdRoute: typeof ProjectsIdDocumentsDocIdRoute
  ProjectsIdPrototypesPrototypeIdRoute: typeof ProjectsIdPrototypesPrototypeIdRoute
  ProjectsIdDocumentsIndexRoute: typeof ProjectsIdDocumentsIndexRoute
  ProjectsIdPrototypesIndexRoute: typeof ProjectsIdPrototypesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/workspaces': {
      id: '/settings/workspaces'
      path: '/settings/workspaces'
      fullPath: '/settings/workspaces'
      preLoaderRoute: typeof SettingsWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/members': {
      id: '/settings/members'
      path: '/settings/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof SettingsMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/mcp': {
      id: '/settings/mcp'
      path: '/settings/mcp'
      fullPath: '/settings/mcp'
      preLoaderRoute: typeof SettingsMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$shareToken': {
      id: '/p/$shareToken'
      path: '/p/$shareToken'
      fullPath: '/p/$shareToken'
      preLoaderRoute: typeof PShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$invitationId': {
      id: '/invite/$invitationId'
      path: '/invite/$invitationId'
      fullPath: '/invite/$invitationId'
      preLoaderRoute: typeof InviteInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$shareToken/': {
      id: '/p/$shareToken/'
      path: '/'
      fullPath: '/p/$shareToken/'
      preLoaderRoute: typeof PShareTokenIndexRouteImport
      parentRoute: typeof PShareTokenRoute
    }
    '/projects/$id/overview': {
      id: '/projects/$id/overview'
      path: '/projects/$id/overview'
      fullPath: '/projects/$id/overview'
      preLoaderRoute: typeof ProjectsIdOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/notes': {
      id: '/projects/$id/notes'
      path: '/projects/$id/notes'
      fullPath: '/projects/$id/notes'
      preLoaderRoute: typeof ProjectsIdNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/list': {
      id: '/projects/$id/list'
      path: '/projects/$id/list'
      fullPath: '/projects/$id/list'
      preLoaderRoute: typeof ProjectsIdListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/inbox': {
      id: '/projects/$id/inbox'
      path: '/projects/$id/inbox'
      fullPath: '/projects/$id/inbox'
      preLoaderRoute: typeof ProjectsIdInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/goals': {
      id: '/projects/$id/goals'
      path: '/projects/$id/goals'
      fullPath: '/projects/$id/goals'
      preLoaderRoute: typeof ProjectsIdGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/flow': {
      id: '/projects/$id/flow'
      path: '/projects/$id/flow'
      fullPath: '/projects/$id/flow'
      preLoaderRoute: typeof ProjectsIdFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/board': {
      id: '/projects/$id/board'
      path: '/projects/$id/board'
      fullPath: '/projects/$id/board'
      preLoaderRoute: typeof ProjectsIdBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$shareToken/prototypes': {
      id: '/p/$shareToken/prototypes'
      path: '/prototypes'
      fullPath: '/p/$shareToken/prototypes'
      preLoaderRoute: typeof PShareTokenPrototypesRouteImport
      parentRoute: typeof PShareTokenRoute
    }
    '/projects/$id/prototypes/': {
      id: '/projects/$id/prototypes/'
      path: '/projects/$id/prototypes'
      fullPath: '/projects/$id/prototypes/'
      preLoaderRoute: typeof ProjectsIdPrototypesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/notes/': {
      id: '/projects/$id/notes/'
      path: '/'
      fullPath: '/projects/$id/notes/'
      preLoaderRoute: typeof ProjectsIdNotesIndexRouteImport
      parentRoute: typeof ProjectsIdNotesRoute
    }
    '/projects/$id/documents/': {
      id: '/projects/$id/documents/'
      path: '/projects/$id/documents'
      fullPath: '/projects/$id/documents/'
      preLoaderRoute: typeof ProjectsIdDocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$shareToken/prototypes/': {
      id: '/p/$shareToken/prototypes/'
      path: '/'
      fullPath: '/p/$shareToken/prototypes/'
      preLoaderRoute: typeof PShareTokenPrototypesIndexRouteImport
      parentRoute: typeof PShareTokenPrototypesRoute
    }
    '/projects/$id/prototypes/$prototypeId': {
      id: '/projects/$id/prototypes/$prototypeId'
      path: '/projects/$id/prototypes/$prototypeId'
      fullPath: '/projects/$id/prototypes/$prototypeId'
      preLoaderRoute: typeof ProjectsIdPrototypesPrototypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/notes/$noteId': {
      id: '/projects/$id/notes/$noteId'
      path: '/$noteId'
      fullPath: '/projects/$id/notes/$noteId'
      preLoaderRoute: typeof ProjectsIdNotesNoteIdRouteImport
      parentRoute: typeof ProjectsIdNotesRoute
    }
    '/projects/$id/documents/$docId': {
      id: '/projects/$id/documents/$docId'
      path: '/projects/$id/documents/$docId'
      fullPath: '/projects/$id/documents/$docId'
      preLoaderRoute: typeof ProjectsIdDocumentsDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$shareToken/prototypes/$prototypeId': {
      id: '/p/$shareToken/prototypes/$prototypeId'
      path: '/$prototypeId'
      fullPath: '/p/$shareToken/prototypes/$prototypeId'
      preLoaderRoute: typeof PShareTokenPrototypesPrototypeIdRouteImport
      parentRoute: typeof PShareTokenPrototypesRoute
    }
  }
}

interface PShareTokenPrototypesRouteChildren {
  PShareTokenPrototypesPrototypeIdRoute: typeof PShareTokenPrototypesPrototypeIdRoute
  PShareTokenPrototypesIndexRoute: typeof PShareTokenPrototypesIndexRoute
}

const PShareTokenPrototypesRouteChildren: PShareTokenPrototypesRouteChildren = {
  PShareTokenPrototypesPrototypeIdRoute: PShareTokenPrototypesPrototypeIdRoute,
  PShareTokenPrototypesIndexRoute: PShareTokenPrototypesIndexRoute,
}

const PShareTokenPrototypesRouteWithChildren =
  PShareTokenPrototypesRoute._addFileChildren(
    PShareTokenPrototypesRouteChildren,
  )

interface PShareTokenRouteChildren {
  PShareTokenPrototypesRoute: typeof PShareTokenPrototypesRouteWithChildren
  PShareTokenIndexRoute: typeof PShareTokenIndexRoute
}

const PShareTokenRouteChildren: PShareTokenRouteChildren = {
  PShareTokenPrototypesRoute: PShareTokenPrototypesRouteWithChildren,
  PShareTokenIndexRoute: PShareTokenIndexRoute,
}

const PShareTokenRouteWithChildren = PShareTokenRoute._addFileChildren(
  PShareTokenRouteChildren,
)

interface ProjectsIdNotesRouteChildren {
  ProjectsIdNotesNoteIdRoute: typeof ProjectsIdNotesNoteIdRoute
  ProjectsIdNotesIndexRoute: typeof ProjectsIdNotesIndexRoute
}

const ProjectsIdNotesRouteChildren: ProjectsIdNotesRouteChildren = {
  ProjectsIdNotesNoteIdRoute: ProjectsIdNotesNoteIdRoute,
  ProjectsIdNotesIndexRoute: ProjectsIdNotesIndexRoute,
}

const ProjectsIdNotesRouteWithChildren = ProjectsIdNotesRoute._addFileChildren(
  ProjectsIdNotesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InviteInvitationIdRoute: InviteInvitationIdRoute,
  PShareTokenRoute: PShareTokenRouteWithChildren,
  SettingsMcpRoute: SettingsMcpRoute,
  SettingsMembersRoute: SettingsMembersRoute,
  SettingsWorkspacesRoute: SettingsWorkspacesRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsIdBoardRoute: ProjectsIdBoardRoute,
  ProjectsIdFlowRoute: ProjectsIdFlowRoute,
  ProjectsIdGoalsRoute: ProjectsIdGoalsRoute,
  ProjectsIdInboxRoute: ProjectsIdInboxRoute,
  ProjectsIdListRoute: ProjectsIdListRoute,
  ProjectsIdNotesRoute: ProjectsIdNotesRouteWithChildren,
  ProjectsIdOverviewRoute: ProjectsIdOverviewRoute,
  ProjectsIdDocumentsDocIdRoute: ProjectsIdDocumentsDocIdRoute,
  ProjectsIdPrototypesPrototypeIdRoute: ProjectsIdPrototypesPrototypeIdRoute,
  ProjectsIdDocumentsIndexRoute: ProjectsIdDocumentsIndexRoute,
  ProjectsIdPrototypesIndexRoute: ProjectsIdPrototypesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
