/** Loose declarations — runtime lives in mcp-tool-handlers.js. */
export type McpToolResult = {
  content: Array<{ type: string; text: string }>;
  structuredContent?: Record<string, unknown>;
  isError?: boolean;
};

export type McpToolHandler = (args?: Record<string, unknown>) => Promise<McpToolResult>;

export declare function createAddArtifactCommentHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createAddCommentHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createAttachFileHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createClaimTaskHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createCompleteAgentRunHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createCompleteGoalHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createCreateArtifactHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createCreateDocumentHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createCreateEdgeHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createCreateFolderHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createCreateGoalHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createCreateNoteHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createCreateProjectHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createCreateShareLinkHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createCreateTaskHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createDeleteEdgeHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createGetArtifactHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createGetDocumentHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createGetGoalHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createGetNextTaskHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createGetNoteHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createGetProjectHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createGetTaskHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createListArtifactCommentsHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createListArtifactsHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createListCommentsHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createListDocumentsHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createListEdgesHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createListGoalsHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createListNotesHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createListProjectsHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createListSubmissionsHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createListTagsHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createListTasksHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createPauseGoalHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createRecordAgentProgressHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createResolveCommentHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createResumeGoalHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createScaffoldProjectFromPlanHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createStartAgentRunHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createSyncPullHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createTriageSubmissionHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createUpdateArtifactHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createUpdateDocumentHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createUpdateFolderHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createUpdateGoalHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createUpdateNoteHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
export declare function createUpdateTaskHandler(dep?: unknown, dep2?: unknown): McpToolHandler;
