name = "plandesk-sync-server"
main = "src/worker.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "plandesk-sync"
database_id = "0fb300c4-681f-4286-91f4-f6e804238899"
