// Generated by scripts/bundle-migrations.mjs from drizzle/. Do not edit;
// run `pnpm --filter @plandesk/db generate` after adding a migration.
export const MIGRATIONS: readonly {
  tag: string;
  when: number;
  hash: string;
  statements: string[];
}[] = [
  {
    "tag": "0000_overrated_karnak",
    "when": 1784275221531,
    "hash": "763b58bc186c5672e90d55f992421b721af1519a483f796cb57269b4ae91d336",
    "statements": [
      "CREATE TABLE `agent_run_events` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`run_id` text NOT NULL,\n\t`message` text NOT NULL,\n\t`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\tFOREIGN KEY (`run_id`) REFERENCES `agent_runs`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE TABLE `agent_runs` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`project_id` text NOT NULL,\n\t`status` text DEFAULT 'running' NOT NULL,\n\t`label` text,\n\t`started_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\t`completed_at` integer,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE TABLE `artifacts` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`project_id` text NOT NULL,\n\t`title` text NOT NULL,\n\t`kind` text DEFAULT 'markdown' NOT NULL,\n\t`content` text DEFAULT '' NOT NULL,\n\t`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\t`updated_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE TABLE `comments` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`project_id` text NOT NULL,\n\t`target_type` text NOT NULL,\n\t`target_id` text NOT NULL,\n\t`passage` text,\n\t`anchor` text,\n\t`body` text NOT NULL,\n\t`resolved` integer DEFAULT false NOT NULL,\n\t`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE TABLE `documents` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`project_id` text NOT NULL,\n\t`title` text NOT NULL,\n\t`body` text,\n\t`status_line` text,\n\t`parent_id` text,\n\t`folder_id` text,\n\t`linked_task_id` text,\n\t`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\t`updated_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`parent_id`) REFERENCES `documents`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`folder_id`) REFERENCES `folders`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`linked_task_id`) REFERENCES `tasks`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE TABLE `edges` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`project_id` text NOT NULL,\n\t`from_task_id` text NOT NULL,\n\t`to_task_id` text NOT NULL,\n\t`label` text,\n\t`arrow_direction` text,\n\t`style` text,\n\t`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`from_task_id`) REFERENCES `tasks`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`to_task_id`) REFERENCES `tasks`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE TABLE `files` (\n\t`id` text NOT NULL,\n\t`project_id` text NOT NULL,\n\t`filename` text NOT NULL,\n\t`mime` text NOT NULL,\n\t`size` integer NOT NULL,\n\t`bytes` blob,\n\t`external_url` text,\n\t`created_at` text NOT NULL,\n\tPRIMARY KEY(`project_id`, `id`),\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE TABLE `folders` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`project_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`parent_folder_id` text,\n\t`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\t`updated_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`parent_folder_id`) REFERENCES `folders`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE TABLE `goals` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`project_id` text NOT NULL,\n\t`objective` text NOT NULL,\n\t`status` text DEFAULT 'active' NOT NULL,\n\t`verification_surface` text,\n\t`constraints` text,\n\t`boundaries` text,\n\t`iteration_policy` text,\n\t`stop_condition` text,\n\t`budget` text,\n\t`last_verification` text,\n\t`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\t`updated_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE TABLE `guest_sessions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`share_id` text NOT NULL,\n\t`project_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`email` text,\n\t`token_hash` text NOT NULL,\n\t`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\t`revoked_at` integer,\n\tFOREIGN KEY (`share_id`) REFERENCES `shares`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE UNIQUE INDEX `guest_sessions_token_hash_unique` ON `guest_sessions` (`token_hash`);",
      "\nCREATE TABLE `notes` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`project_id` text NOT NULL,\n\t`title` text NOT NULL,\n\t`body` text,\n\t`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\t`updated_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE TABLE `projects` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`org_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`description` text,\n\t`canvas_layout` text,\n\t`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\t`updated_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL\n);\n",
      "\nCREATE TABLE `share_submissions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`project_id` text NOT NULL,\n\t`hosted_share_id` text NOT NULL,\n\t`participant_name` text NOT NULL,\n\t`title` text NOT NULL,\n\t`body` text,\n\t`severity` text,\n\t`task_ref` text,\n\t`status` text DEFAULT 'pending' NOT NULL,\n\t`linked_task_id` text,\n\t`created_at` integer NOT NULL,\n\t`pulled_at` integer NOT NULL,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`linked_task_id`) REFERENCES `tasks`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE TABLE `shares` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`project_id` text NOT NULL,\n\t`audience_name` text NOT NULL,\n\t`mode` text DEFAULT 'invite' NOT NULL,\n\t`token_hash` text NOT NULL,\n\t`permissions` text NOT NULL,\n\t`policy` text NOT NULL,\n\t`invited_emails` text,\n\t`expires_at` integer,\n\t`revoked_at` integer,\n\t`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE TABLE `sync_remotes` (\n\t`project_id` text PRIMARY KEY NOT NULL,\n\t`server_url` text NOT NULL,\n\t`global_project_id` text NOT NULL,\n\t`sync_token` text NOT NULL,\n\t`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\t`updated_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE TABLE `sync_state` (\n\t`project_id` text PRIMARY KEY NOT NULL,\n\t`pull_cursor` text,\n\t`updated_at` integer NOT NULL,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE TABLE `tags` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`project_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`color` text,\n\t`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE UNIQUE INDEX `tags_project_id_name_unique` ON `tags` (`project_id`,`name`);",
      "\nCREATE TABLE `task_tags` (\n\t`task_id` text NOT NULL,\n\t`tag_id` text NOT NULL,\n\tPRIMARY KEY(`task_id`, `tag_id`),\n\tFOREIGN KEY (`task_id`) REFERENCES `tasks`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`tag_id`) REFERENCES `tags`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE TABLE `tasks` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`project_id` text NOT NULL,\n\t`goal_id` text NOT NULL,\n\t`label` text NOT NULL,\n\t`status` text DEFAULT 'todo' NOT NULL,\n\t`description` text,\n\t`x` real DEFAULT 0 NOT NULL,\n\t`y` real DEFAULT 0 NOT NULL,\n\t`assignee` text,\n\t`due_date` integer,\n\t`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\t`updated_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`goal_id`) REFERENCES `goals`(`id`) ON UPDATE no action ON DELETE no action\n);\n"
    ]
  },
  {
    "tag": "0001_daffy_hercules",
    "when": 1784375156077,
    "hash": "f8503b6b16c97404b801151370fc7fc6c80adef5b703fbdbceace0fc32e9fd0c",
    "statements": [
      "ALTER TABLE `projects` ADD `workspace_id` text DEFAULT '00000000-0000-4000-8000-0000000000a2' NOT NULL;"
    ]
  },
  {
    "tag": "0002_ws_share",
    "when": 1784386851159,
    "hash": "5b999300689c0bdf06ef5ccb22962d7cbbd722d3a09381d41c3f49c1157200c6",
    "statements": [
      "PRAGMA foreign_keys=OFF;",
      "\nCREATE TABLE `__new_guest_sessions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`share_id` text NOT NULL,\n\t`project_id` text,\n\t`workspace_id` text,\n\t`name` text NOT NULL,\n\t`email` text,\n\t`token_hash` text NOT NULL,\n\t`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\t`revoked_at` integer,\n\tFOREIGN KEY (`share_id`) REFERENCES `shares`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nINSERT INTO `__new_guest_sessions`(\"id\", \"share_id\", \"project_id\", \"workspace_id\", \"name\", \"email\", \"token_hash\", \"created_at\", \"revoked_at\") SELECT \"id\", \"share_id\", \"project_id\", NULL AS \"workspace_id\", \"name\", \"email\", \"token_hash\", \"created_at\", \"revoked_at\" FROM `guest_sessions`;",
      "\nDROP TABLE `guest_sessions`;",
      "\nALTER TABLE `__new_guest_sessions` RENAME TO `guest_sessions`;",
      "\nCREATE UNIQUE INDEX `guest_sessions_token_hash_unique` ON `guest_sessions` (`token_hash`);",
      "\nCREATE TABLE `__new_shares` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`project_id` text,\n\t`workspace_id` text,\n\t`audience_name` text NOT NULL,\n\t`mode` text DEFAULT 'invite' NOT NULL,\n\t`token_hash` text NOT NULL,\n\t`permissions` text NOT NULL,\n\t`policy` text NOT NULL,\n\t`invited_emails` text,\n\t`expires_at` integer,\n\t`revoked_at` integer,\n\t`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nINSERT INTO `__new_shares`(\"id\", \"project_id\", \"workspace_id\", \"audience_name\", \"mode\", \"token_hash\", \"permissions\", \"policy\", \"invited_emails\", \"expires_at\", \"revoked_at\", \"created_at\") SELECT \"id\", \"project_id\", NULL AS \"workspace_id\", \"audience_name\", \"mode\", \"token_hash\", \"permissions\", \"policy\", \"invited_emails\", \"expires_at\", \"revoked_at\", \"created_at\" FROM `shares`;",
      "\nDROP TABLE `shares`;",
      "\nALTER TABLE `__new_shares` RENAME TO `shares`;",
      "\nPRAGMA foreign_keys=ON;"
    ]
  },
  {
    "tag": "0003_poly_edges",
    "when": 1784400000000,
    "hash": "2d4d1d8132cd9cc3b81d30c7fede55a1a1fb778c6c7def612f349e26071cb32a",
    "statements": [
      "ALTER TABLE `edges` ADD `from_type` text;",
      "\nALTER TABLE `edges` ADD `from_id` text;",
      "\nALTER TABLE `edges` ADD `to_type` text;",
      "\nALTER TABLE `edges` ADD `to_id` text;",
      "\nUPDATE `edges` SET `from_type` = 'task', `from_id` = `from_task_id`, `to_type` = 'task', `to_id` = `to_task_id`;",
      "\nINSERT INTO `edges` (`id`, `project_id`, `from_task_id`, `to_task_id`, `from_type`, `from_id`, `to_type`, `to_id`, `label`, `arrow_direction`, `style`, `created_at`)\nSELECT\n\tlower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(6))),\n\t`project_id`,\n\t`linked_task_id`,\n\t`linked_task_id`,\n\t'document',\n\t`id`,\n\t'task',\n\t`linked_task_id`,\n\t'documents',\n\tNULL,\n\tNULL,\n\tcast((julianday('now') - 2440587.5)*86400000 as integer)\nFROM `documents`\nWHERE `linked_task_id` IS NOT NULL;",
      "\nCREATE INDEX `edges_project_from_idx` ON `edges` (`project_id`, `from_type`, `from_id`);",
      "\nCREATE INDEX `edges_project_to_idx` ON `edges` (`project_id`, `to_type`, `to_id`);\n"
    ]
  },
  {
    "tag": "0004_legacy_edge_cols_nullable",
    "when": 1784988578999,
    "hash": "0ef11123ffa290d8e2947248471f214c2764fc6fbcdeea7ad7bbf6641dc769ed",
    "statements": [
      "PRAGMA foreign_keys=OFF;",
      "\nCREATE TABLE `__new_edges` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`project_id` text NOT NULL,\n\t`from_task_id` text,\n\t`to_task_id` text,\n\t`from_type` text,\n\t`from_id` text,\n\t`to_type` text,\n\t`to_id` text,\n\t`label` text,\n\t`arrow_direction` text,\n\t`style` text,\n\t`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`from_task_id`) REFERENCES `tasks`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`to_task_id`) REFERENCES `tasks`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nINSERT INTO `__new_edges`(\"id\", \"project_id\", \"from_task_id\", \"to_task_id\", \"from_type\", \"from_id\", \"to_type\", \"to_id\", \"label\", \"arrow_direction\", \"style\", \"created_at\") SELECT \"id\", \"project_id\", \"from_task_id\", \"to_task_id\", \"from_type\", \"from_id\", \"to_type\", \"to_id\", \"label\", \"arrow_direction\", \"style\", \"created_at\" FROM `edges`;",
      "\nDROP TABLE `edges`;",
      "\nALTER TABLE `__new_edges` RENAME TO `edges`;",
      "\nPRAGMA foreign_keys=ON;",
      "\nCREATE INDEX `edges_project_from_idx` ON `edges` (`project_id`,`from_type`,`from_id`);",
      "\nCREATE INDEX `edges_project_to_idx` ON `edges` (`project_id`,`to_type`,`to_id`);"
    ]
  },
  {
    "tag": "0005_contract_drop_legacy_link_cols",
    "when": 1785000000000,
    "hash": "3322d77a2491571aa84bd6bf4accf58cd3a99ec36524d3eca4d799462808f25d",
    "statements": [
      "-- Contract: drop task-only edge columns and documents.linked_task_id.\n-- Typed endpoints become the sole, non-nullable shape of an edge.\n-- Defensive: ensure every remaining linked_task_id still has a document→task edge\n-- before the column is dropped (covers dual-write gaps).\nPRAGMA foreign_keys=OFF;",
      "\nINSERT INTO `edges` (`id`, `project_id`, `from_task_id`, `to_task_id`, `from_type`, `from_id`, `to_type`, `to_id`, `label`, `arrow_direction`, `style`, `created_at`)\nSELECT\n\tlower(hex(randomblob(4)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(2)) || '-' || hex(randomblob(6))),\n\t`project_id`,\n\tNULL,\n\tNULL,\n\t'document',\n\t`id`,\n\t'task',\n\t`linked_task_id`,\n\t'documents',\n\tNULL,\n\tNULL,\n\tcast((julianday('now') - 2440587.5)*86400000 as integer)\nFROM `documents` AS d\nWHERE `linked_task_id` IS NOT NULL\n\tAND NOT EXISTS (\n\t\tSELECT 1 FROM `edges` AS e\n\t\tWHERE e.`from_type` = 'document'\n\t\t\tAND e.`from_id` = d.`id`\n\t\t\tAND e.`to_type` = 'task'\n\t\t\tAND e.`to_id` = d.`linked_task_id`\n\t);",
      "\nCREATE TABLE `__new_edges` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`project_id` text NOT NULL,\n\t`from_type` text NOT NULL,\n\t`from_id` text NOT NULL,\n\t`to_type` text NOT NULL,\n\t`to_id` text NOT NULL,\n\t`label` text,\n\t`arrow_direction` text,\n\t`style` text,\n\t`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nINSERT INTO `__new_edges`(\"id\", \"project_id\", \"from_type\", \"from_id\", \"to_type\", \"to_id\", \"label\", \"arrow_direction\", \"style\", \"created_at\")\nSELECT\n\t\"id\",\n\t\"project_id\",\n\tCOALESCE(\"from_type\", 'task'),\n\tCOALESCE(\"from_id\", \"from_task_id\"),\n\tCOALESCE(\"to_type\", 'task'),\n\tCOALESCE(\"to_id\", \"to_task_id\"),\n\t\"label\",\n\t\"arrow_direction\",\n\t\"style\",\n\t\"created_at\"\nFROM `edges`\nWHERE COALESCE(\"from_id\", \"from_task_id\") IS NOT NULL\n\tAND COALESCE(\"to_id\", \"to_task_id\") IS NOT NULL;",
      "\nDROP TABLE `edges`;",
      "\nALTER TABLE `__new_edges` RENAME TO `edges`;",
      "\nCREATE INDEX `edges_project_from_idx` ON `edges` (`project_id`,`from_type`,`from_id`);",
      "\nCREATE INDEX `edges_project_to_idx` ON `edges` (`project_id`,`to_type`,`to_id`);",
      "\nCREATE TABLE `__new_documents` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`project_id` text NOT NULL,\n\t`title` text NOT NULL,\n\t`body` text,\n\t`status_line` text,\n\t`parent_id` text,\n\t`folder_id` text,\n\t`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\t`updated_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`parent_id`) REFERENCES `documents`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`folder_id`) REFERENCES `folders`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nINSERT INTO `__new_documents`(\"id\", \"project_id\", \"title\", \"body\", \"status_line\", \"parent_id\", \"folder_id\", \"created_at\", \"updated_at\")\nSELECT \"id\", \"project_id\", \"title\", \"body\", \"status_line\", \"parent_id\", \"folder_id\", \"created_at\", \"updated_at\" FROM `documents`;",
      "\nDROP TABLE `documents`;",
      "\nALTER TABLE `__new_documents` RENAME TO `documents`;",
      "\nPRAGMA foreign_keys=ON;\n"
    ]
  },
  {
    "tag": "0006_oval_silhouette",
    "when": 1785441250003,
    "hash": "c6ce39f68109cbf6c656c895153fe9573f9accab10c0c8502948b13acc590c1e",
    "statements": [
      "ALTER TABLE `projects` ADD `repo_url` text;",
      "\nALTER TABLE `projects` ADD `folder_path` text;"
    ]
  },
  {
    "tag": "0007_blushing_raza",
    "when": 1785447415931,
    "hash": "56ec99271697bf9869ebb8b408341429c69e4b70f707795793b8f06dad7e25d1",
    "statements": [
      "ALTER TABLE `tasks` ADD `commit_refs` text;"
    ]
  },
  {
    "tag": "0008_woozy_colossus",
    "when": 1785494687446,
    "hash": "d45934079ca3d87dad279430d3505c8f5f4d79cf1b26cc57269b83858d444b58",
    "statements": [
      "ALTER TABLE `tasks` ADD `kind` text DEFAULT 'build' NOT NULL;"
    ]
  },
  {
    "tag": "0009_thick_valeria_richards",
    "when": 1785515454193,
    "hash": "bc490e8b561c49bdc23b2d2ae1efb4955a71735ec8b0fc1d8f1eef3408db5adb",
    "statements": [
      "CREATE TABLE `revisions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`project_id` text NOT NULL,\n\t`target_type` text NOT NULL,\n\t`target_id` text NOT NULL,\n\t`snapshot` text NOT NULL,\n\t`changed_fields` text NOT NULL,\n\t`author` text NOT NULL,\n\t`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE INDEX `revisions_target_idx` ON `revisions` (`target_type`,`target_id`,`created_at`);"
    ]
  },
  {
    "tag": "0010_smart_sphinx",
    "when": 1785528770029,
    "hash": "6045bf3b0d8bb290c928d1854e34672586c6f5ac1ddd42663a7c63dfe9d2fd11",
    "statements": [
      "ALTER TABLE `tasks` ADD `priority` text;",
      "\n-- Additive severity-tag backfill: map severity:* tags onto the new column where\n-- priority is still null. Tags stay attached; re-running is a no-op because each\n-- UPDATE only touches rows with priority IS NULL.\nUPDATE `tasks` SET `priority` = 'high' WHERE `priority` IS NULL AND `id` IN (\n\tSELECT `task_tags`.`task_id` FROM `task_tags`\n\tINNER JOIN `tags` ON `tags`.`id` = `task_tags`.`tag_id`\n\tWHERE `tags`.`name` = 'severity:high'\n);",
      "\nUPDATE `tasks` SET `priority` = 'medium' WHERE `priority` IS NULL AND `id` IN (\n\tSELECT `task_tags`.`task_id` FROM `task_tags`\n\tINNER JOIN `tags` ON `tags`.`id` = `task_tags`.`tag_id`\n\tWHERE `tags`.`name` = 'severity:medium'\n);",
      "\nUPDATE `tasks` SET `priority` = 'low' WHERE `priority` IS NULL AND `id` IN (\n\tSELECT `task_tags`.`task_id` FROM `task_tags`\n\tINNER JOIN `tags` ON `tags`.`id` = `task_tags`.`tag_id`\n\tWHERE `tags`.`name` = 'severity:low'\n);\n"
    ]
  },
  {
    "tag": "0011_hard_marvex",
    "when": 1785563499629,
    "hash": "0842719f46ac8c2511acbf8243ca4cdf01b6d8c8f631e2aff2a03e85322073a7",
    "statements": [
      "CREATE TABLE `views` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`project_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`config` text NOT NULL,\n\t`position` integer DEFAULT 0 NOT NULL,\n\t`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\t`updated_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE INDEX `views_project_id_position_idx` ON `views` (`project_id`,`position`);"
    ]
  },
  {
    "tag": "0012_long_ted_forrester",
    "when": 1785583167439,
    "hash": "69e96ae2205dd385638fc40769f05d163eaf2e6ecb7e4f4c9b071195dae193f9",
    "statements": [
      "ALTER TABLE `projects` ADD `owner_id` text;",
      "\nALTER TABLE `projects` ADD `overview_document_id` text REFERENCES documents(id);"
    ]
  },
  {
    "tag": "0013_flimsy_sharon_ventura",
    "when": 1785672989882,
    "hash": "01c28ec671a1943f1632b510c3974a1e4f981520e5a14391aaad35c64b02e391",
    "statements": [
      "CREATE TABLE `prototypes` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`project_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`viewport_width` real NOT NULL,\n\t`viewport_height` real NOT NULL,\n\t`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\t`updated_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nALTER TABLE `artifacts` ADD `prototype_id` text REFERENCES prototypes(id);",
      "\nALTER TABLE `artifacts` ADD `x` real;",
      "\nALTER TABLE `artifacts` ADD `y` real;"
    ]
  },
  {
    "tag": "0014_true_plazm",
    "when": 1785681954986,
    "hash": "f3d9a8b2099a4eddc1c72d45c27bacf4c154ea909677429b1df81ea7e22cdb22",
    "statements": [
      "CREATE TABLE `prototype_links` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`project_id` text NOT NULL,\n\t`from_artifact_id` text NOT NULL,\n\t`to_artifact_id` text,\n\t`raw_target` text NOT NULL,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`from_artifact_id`) REFERENCES `artifacts`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`to_artifact_id`) REFERENCES `artifacts`(`id`) ON UPDATE no action ON DELETE no action\n);\n"
    ]
  },
  {
    "tag": "0015_pale_bishop",
    "when": 1785682312693,
    "hash": "d7216ee2b704b9ea69647cfcd526b6ce33a914cae7f8f09e3fcc2d8f3c3e4279",
    "statements": [
      "ALTER TABLE `prototypes` ADD `folder_id` text REFERENCES folders(id);"
    ]
  },
  {
    "tag": "0016_mature_mockingbird",
    "when": 1785685599276,
    "hash": "b1575b3d5abfad09ce0e796a35a55e082d5b906fde087eb35957a6e179d240c8",
    "statements": [
      "CREATE TABLE `render_tokens` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`org_id` text NOT NULL,\n\t`project_id` text NOT NULL,\n\t`token_hash` text NOT NULL,\n\t`prototype_ids` text NOT NULL,\n\t`expires_at` integer NOT NULL,\n\t`revoked_at` integer,\n\t`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE UNIQUE INDEX `render_tokens_token_hash_unique` ON `render_tokens` (`token_hash`);"
    ]
  },
  {
    "tag": "0017_robust_old_lace",
    "when": 1785703927322,
    "hash": "e1b2ed0b4ccad5abffe5edfab1bab17997eb3fd026e617859638abbf2ef37606",
    "statements": [
      "ALTER TABLE `tasks` ADD `lane` text;",
      "\nALTER TABLE `tasks` ADD `severity` text;",
      "\nCREATE TABLE `task_field_migration_conflicts` (\n\t`task_id` text NOT NULL,\n\t`field` text NOT NULL,\n\t`tag_values` text NOT NULL,\n\tPRIMARY KEY(`task_id`, `field`)\n);",
      "\nINSERT INTO `task_field_migration_conflicts` (`task_id`, `field`, `tag_values`)\nSELECT `task_tags`.`task_id`, 'lane', group_concat(DISTINCT substr(`tags`.`name`, 6))\nFROM `task_tags`\nINNER JOIN `tags` ON `tags`.`id` = `task_tags`.`tag_id`\nWHERE `tags`.`name` IN ('lane:auto', 'lane:approve', 'lane:full')\nGROUP BY `task_tags`.`task_id`\nHAVING count(DISTINCT substr(`tags`.`name`, 6)) > 1;",
      "\nINSERT INTO `task_field_migration_conflicts` (`task_id`, `field`, `tag_values`)\nSELECT `task_tags`.`task_id`, 'severity', group_concat(DISTINCT CASE\n\tWHEN `tags`.`name` LIKE 'sev:%' THEN substr(`tags`.`name`, 5)\n\tELSE substr(`tags`.`name`, 10)\nEND)\nFROM `task_tags`\nINNER JOIN `tags` ON `tags`.`id` = `task_tags`.`tag_id`\nWHERE `tags`.`name` IN (\n\t'sev:low', 'sev:medium', 'sev:high',\n\t'severity:low', 'severity:medium', 'severity:high'\n)\nGROUP BY `task_tags`.`task_id`\nHAVING count(DISTINCT CASE\n\tWHEN `tags`.`name` LIKE 'sev:%' THEN substr(`tags`.`name`, 5)\n\tELSE substr(`tags`.`name`, 10)\nEND) > 1;",
      "\nUPDATE `tasks`\nSET `lane` = (\n\tSELECT MIN(substr(`tags`.`name`, 6))\n\tFROM `task_tags`\n\tINNER JOIN `tags` ON `tags`.`id` = `task_tags`.`tag_id`\n\tWHERE `task_tags`.`task_id` = `tasks`.`id`\n\t  AND `tags`.`name` IN ('lane:auto', 'lane:approve', 'lane:full')\n)\nWHERE `tasks`.`lane` IS NULL\n  AND `tasks`.`id` IN (\n\tSELECT `task_tags`.`task_id`\n\tFROM `task_tags`\n\tINNER JOIN `tags` ON `tags`.`id` = `task_tags`.`tag_id`\n\tWHERE `tags`.`name` IN ('lane:auto', 'lane:approve', 'lane:full')\n\tGROUP BY `task_tags`.`task_id`\n\tHAVING count(DISTINCT substr(`tags`.`name`, 6)) = 1\n);",
      "\nUPDATE `tasks`\nSET `severity` = (\n\tSELECT MIN(CASE\n\t\tWHEN `tags`.`name` LIKE 'sev:%' THEN substr(`tags`.`name`, 5)\n\t\tELSE substr(`tags`.`name`, 10)\n\tEND)\n\tFROM `task_tags`\n\tINNER JOIN `tags` ON `tags`.`id` = `task_tags`.`tag_id`\n\tWHERE `task_tags`.`task_id` = `tasks`.`id`\n\t  AND `tags`.`name` IN (\n\t\t'sev:low', 'sev:medium', 'sev:high',\n\t\t'severity:low', 'severity:medium', 'severity:high'\n\t  )\n)\nWHERE `tasks`.`severity` IS NULL\n  AND `tasks`.`id` IN (\n\tSELECT `task_tags`.`task_id`\n\tFROM `task_tags`\n\tINNER JOIN `tags` ON `tags`.`id` = `task_tags`.`tag_id`\n\tWHERE `tags`.`name` IN (\n\t\t'sev:low', 'sev:medium', 'sev:high',\n\t\t'severity:low', 'severity:medium', 'severity:high'\n\t)\n\tGROUP BY `task_tags`.`task_id`\n\tHAVING count(DISTINCT CASE\n\t\tWHEN `tags`.`name` LIKE 'sev:%' THEN substr(`tags`.`name`, 5)\n\t\tELSE substr(`tags`.`name`, 10)\n\tEND) = 1\n);\n"
    ]
  },
  {
    "tag": "0018_square_the_liberteens",
    "when": 1785704768969,
    "hash": "e58a5513d30c7ca39e02f08e80f1178f1e8fa09d978ed6b3413bf827ad012c1f",
    "statements": [
      "ALTER TABLE `goals` ADD `name` text;",
      "\nCREATE UNIQUE INDEX `goals_project_id_name_unique` ON `goals` (`project_id`,`name`);"
    ]
  },
  {
    "tag": "0019_current_goal_id",
    "when": 1785753594862,
    "hash": "fb488c56a48a39cbe679f92a90742d93a03c3e375406434c21a3cffed3da1ff1",
    "statements": [
      "ALTER TABLE `projects` ADD `current_goal_id` text REFERENCES goals(id);",
      "\nUPDATE `projects`\nSET `current_goal_id` = (\n  SELECT `g`.`id`\n  FROM `goals` AS `g`\n  WHERE `g`.`project_id` = `projects`.`id`\n    AND `g`.`status` = 'active'\n  ORDER BY `g`.`created_at` DESC, `g`.`id` DESC\n  LIMIT 1\n)\nWHERE `current_goal_id` IS NULL;"
    ]
  },
  {
    "tag": "0020_elite_shiva",
    "when": 1786889915393,
    "hash": "cfeaec45d5819b1db21522cd6a00f25ce06b0260cf00faa6d1ee597f841e51bc",
    "statements": [
      "ALTER TABLE `artifacts` ADD `folder_id` text REFERENCES folders(id);"
    ]
  },
  {
    "tag": "0021_lame_typhoid_mary",
    "when": 1791027615481,
    "hash": "7befcfbc9f22b2be722749fe4620ff5b4a23a133c5421ef2557c651cbc110362",
    "statements": [
      "PRAGMA foreign_keys=OFF;",
      "\nCREATE TABLE `__new_tasks` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`project_id` text NOT NULL,\n\t`goal_id` text,\n\t`label` text NOT NULL,\n\t`status` text DEFAULT 'todo' NOT NULL,\n\t`kind` text DEFAULT 'build' NOT NULL,\n\t`priority` text,\n\t`lane` text,\n\t`severity` text,\n\t`description` text,\n\t`x` real DEFAULT 0 NOT NULL,\n\t`y` real DEFAULT 0 NOT NULL,\n\t`assignee` text,\n\t`due_date` integer,\n\t`commit_refs` text,\n\t`created_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\t`updated_at` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,\n\tFOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`goal_id`) REFERENCES `goals`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nINSERT INTO `__new_tasks`(\"id\", \"project_id\", \"goal_id\", \"label\", \"status\", \"kind\", \"priority\", \"lane\", \"severity\", \"description\", \"x\", \"y\", \"assignee\", \"due_date\", \"commit_refs\", \"created_at\", \"updated_at\") SELECT \"id\", \"project_id\", \"goal_id\", \"label\", \"status\", \"kind\", \"priority\", \"lane\", \"severity\", \"description\", \"x\", \"y\", \"assignee\", \"due_date\", \"commit_refs\", \"created_at\", \"updated_at\" FROM `tasks`;",
      "\nDROP TABLE `tasks`;",
      "\nALTER TABLE `__new_tasks` RENAME TO `tasks`;",
      "\nPRAGMA foreign_keys=ON;"
    ]
  },
  {
    "tag": "0022_search_index",
    "when": 1791030455137,
    "hash": "22b9da8837a6971b080e54b0ad1d4760504582581d2c5ee069834d3f976dc2fd",
    "statements": [
      "CREATE VIRTUAL TABLE `search_index` USING fts5(\n\t`kind` UNINDEXED,\n\t`item_id` UNINDEXED,\n\t`project_id` UNINDEXED,\n\t`title`,\n\t`body`,\n\ttokenize='trigram'\n);\n",
      "\n-- One FTS table serves every tenant, and its kind/item_id columns are not\n-- indexed: finding a row by them is a full scan. This map lets the triggers\n-- address an index row by its rowid instead.\nCREATE TABLE `search_index_rowids` (\n\t`kind` text NOT NULL,\n\t`item_id` text NOT NULL,\n\t`fts_rowid` integer NOT NULL,\n\tPRIMARY KEY(`kind`, `item_id`)\n) WITHOUT ROWID;\n",
      "\nCREATE TRIGGER `documents_search_index_ai` AFTER INSERT ON `documents` BEGIN\n\tINSERT INTO `search_index`(`kind`, `item_id`, `project_id`, `title`, `body`)\n\tVALUES ('document', NEW.`id`, NEW.`project_id`, NEW.`title`, COALESCE(NEW.`body`, ''));\n\tINSERT INTO `search_index_rowids`(`kind`, `item_id`, `fts_rowid`)\n\tVALUES ('document', NEW.`id`, last_insert_rowid());\nEND;\n",
      "\nCREATE TRIGGER `documents_search_index_au` AFTER UPDATE OF `project_id`, `title`, `body` ON `documents` BEGIN\n\tDELETE FROM `search_index` WHERE rowid =\n\t\t(SELECT `fts_rowid` FROM `search_index_rowids` WHERE `kind` = 'document' AND `item_id` = OLD.`id`);\n\tDELETE FROM `search_index_rowids` WHERE `kind` = 'document' AND `item_id` = OLD.`id`;\n\tINSERT INTO `search_index`(`kind`, `item_id`, `project_id`, `title`, `body`)\n\tVALUES ('document', NEW.`id`, NEW.`project_id`, NEW.`title`, COALESCE(NEW.`body`, ''));\n\tINSERT INTO `search_index_rowids`(`kind`, `item_id`, `fts_rowid`)\n\tVALUES ('document', NEW.`id`, last_insert_rowid());\nEND;\n",
      "\nCREATE TRIGGER `documents_search_index_ad` AFTER DELETE ON `documents` BEGIN\n\tDELETE FROM `search_index` WHERE rowid =\n\t\t(SELECT `fts_rowid` FROM `search_index_rowids` WHERE `kind` = 'document' AND `item_id` = OLD.`id`);\n\tDELETE FROM `search_index_rowids` WHERE `kind` = 'document' AND `item_id` = OLD.`id`;\nEND;\n",
      "\nCREATE TRIGGER `notes_search_index_ai` AFTER INSERT ON `notes` BEGIN\n\tINSERT INTO `search_index`(`kind`, `item_id`, `project_id`, `title`, `body`)\n\tVALUES ('note', NEW.`id`, NEW.`project_id`, NEW.`title`, COALESCE(NEW.`body`, ''));\n\tINSERT INTO `search_index_rowids`(`kind`, `item_id`, `fts_rowid`)\n\tVALUES ('note', NEW.`id`, last_insert_rowid());\nEND;\n",
      "\nCREATE TRIGGER `notes_search_index_au` AFTER UPDATE OF `project_id`, `title`, `body` ON `notes` BEGIN\n\tDELETE FROM `search_index` WHERE rowid =\n\t\t(SELECT `fts_rowid` FROM `search_index_rowids` WHERE `kind` = 'note' AND `item_id` = OLD.`id`);\n\tDELETE FROM `search_index_rowids` WHERE `kind` = 'note' AND `item_id` = OLD.`id`;\n\tINSERT INTO `search_index`(`kind`, `item_id`, `project_id`, `title`, `body`)\n\tVALUES ('note', NEW.`id`, NEW.`project_id`, NEW.`title`, COALESCE(NEW.`body`, ''));\n\tINSERT INTO `search_index_rowids`(`kind`, `item_id`, `fts_rowid`)\n\tVALUES ('note', NEW.`id`, last_insert_rowid());\nEND;\n",
      "\nCREATE TRIGGER `notes_search_index_ad` AFTER DELETE ON `notes` BEGIN\n\tDELETE FROM `search_index` WHERE rowid =\n\t\t(SELECT `fts_rowid` FROM `search_index_rowids` WHERE `kind` = 'note' AND `item_id` = OLD.`id`);\n\tDELETE FROM `search_index_rowids` WHERE `kind` = 'note' AND `item_id` = OLD.`id`;\nEND;\n",
      "\nCREATE TRIGGER `tasks_search_index_ai` AFTER INSERT ON `tasks` BEGIN\n\tINSERT INTO `search_index`(`kind`, `item_id`, `project_id`, `title`, `body`)\n\tVALUES ('task', NEW.`id`, NEW.`project_id`, NEW.`label`, COALESCE(NEW.`description`, ''));\n\tINSERT INTO `search_index_rowids`(`kind`, `item_id`, `fts_rowid`)\n\tVALUES ('task', NEW.`id`, last_insert_rowid());\nEND;\n",
      "\nCREATE TRIGGER `tasks_search_index_au` AFTER UPDATE OF `project_id`, `label`, `description` ON `tasks` BEGIN\n\tDELETE FROM `search_index` WHERE rowid =\n\t\t(SELECT `fts_rowid` FROM `search_index_rowids` WHERE `kind` = 'task' AND `item_id` = OLD.`id`);\n\tDELETE FROM `search_index_rowids` WHERE `kind` = 'task' AND `item_id` = OLD.`id`;\n\tINSERT INTO `search_index`(`kind`, `item_id`, `project_id`, `title`, `body`)\n\tVALUES ('task', NEW.`id`, NEW.`project_id`, NEW.`label`, COALESCE(NEW.`description`, ''));\n\tINSERT INTO `search_index_rowids`(`kind`, `item_id`, `fts_rowid`)\n\tVALUES ('task', NEW.`id`, last_insert_rowid());\nEND;\n",
      "\nCREATE TRIGGER `tasks_search_index_ad` AFTER DELETE ON `tasks` BEGIN\n\tDELETE FROM `search_index` WHERE rowid =\n\t\t(SELECT `fts_rowid` FROM `search_index_rowids` WHERE `kind` = 'task' AND `item_id` = OLD.`id`);\n\tDELETE FROM `search_index_rowids` WHERE `kind` = 'task' AND `item_id` = OLD.`id`;\nEND;\n",
      "\nINSERT INTO `search_index`(`kind`, `item_id`, `project_id`, `title`, `body`)\nSELECT 'document', `id`, `project_id`, `title`, COALESCE(`body`, '') FROM `documents`;\n",
      "\nINSERT INTO `search_index`(`kind`, `item_id`, `project_id`, `title`, `body`)\nSELECT 'note', `id`, `project_id`, `title`, COALESCE(`body`, '') FROM `notes`;\n",
      "\nINSERT INTO `search_index`(`kind`, `item_id`, `project_id`, `title`, `body`)\nSELECT 'task', `id`, `project_id`, `label`, COALESCE(`description`, '') FROM `tasks`;\n",
      "\nINSERT INTO `search_index_rowids`(`kind`, `item_id`, `fts_rowid`)\nSELECT `kind`, `item_id`, rowid FROM `search_index`;\n"
    ]
  },
  {
    "tag": "0023_wandering_clea",
    "when": 1791032947624,
    "hash": "d9b417f94abacdd3ab4ab7c6e619582c4acece5ab75b32a59816b48d4000e0c1",
    "statements": [
      "ALTER TABLE `documents` ADD `source_path` text;",
      "\nALTER TABLE `documents` ADD `verified_at` integer;",
      "\nALTER TABLE `documents` ADD `verified_ref` text;",
      "\nALTER TABLE `tasks` ADD `verified_at` integer;",
      "\nALTER TABLE `tasks` ADD `verified_ref` text;"
    ]
  },
  {
    "tag": "0024_sloppy_dark_phoenix",
    "when": 1791035238684,
    "hash": "4cc5702ca3e765d6d23ad93bfa8dd4e8c3d772924bc96c58c0435da3931bf1f1",
    "statements": [
      "DROP TABLE `sync_remotes`;"
    ]
  }
];
